live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x555753"
blue = "0x729FCF"
cyan = "0x34E2E2"
green = "0x8AE234"
magenta = "0xAD7FA8"
red = "0xEF2929"
white = "0xEEEEEC"
yellow = "0xFCE94F"

[colors.normal]
black = "0x2E3436"
blue = "0x3465A4"
cyan = "0x06989A"
green = "0x00CD00"
magenta = "0x75507B"
red = "0xcc0000"
white = "0xD3D7CF"
yellow = "0xC4A000"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
render_timer = false

[font]
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "monospace"
style = "Retina"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "LBracket"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Q"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Q"
mode = "Vi"

[[keyboard.bindings]]
action = "Last"
key = "Key5"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Bracket"
key = "Key6"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "Key7"
mode = "Vi"
mods = "Shift"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 50000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/usr/local/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 2
y = 2
