# Configuration for Alacritty, the GPU enhanced terminal emulator


# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
# env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  # To install alacritty terminfo, run the following command from alacritty's
  # root folder:
  #   sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
  # TERM: alacritty

window:
  # Window dimensions in character columns and lines
  # (changes require restart)
  dimensions:
    columns: 120
    lines: 50
  dynamic_title: true

  # Adds this many blank pixels of padding around the window
  # Units are physical pixels; this is not DPI aware.
  # (change requires restart)
  padding:
    x: 2
    y: 2

  # Window decorations
  # Setting this to none will result in window without borders and title bar.
  decorations: none
  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Maximized

# The FreeType rasterizer needs to know the device DPI for best results
# (changes require restart)
dpi:
  x: 96.0
  y: 96.0

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: false

# Font configuration (changes require restart)
font:
  normal:
    family: monospace
    style: Regular
  bold:
    family: monospace
    style: Bold
  italic:
    family: monospace
    style: Italic
  size: 11.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

debug:
  # Should display the render timer
  render_timer: false

cursor:
  # Cursor style
  #
  # Values for 'cursor.style':
  #   - Block
  #   - Underline
  #   - Beam
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

# color_start
# /home/zach/.config/alacritty-theme/themes/tomorrow_night_bright.yaml
# Colors (Tomorrow Night Bright)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xeaeaea'

  # Normal colors
  normal:
    black:   '0x2E3436'
    red:     '0xcc0000'
    green:   '0x00CD00'
    yellow:  '0xC4A000'
    blue:    '0x3465A4'
    magenta: '0x75507B'
    cyan:    '0x06989A'
    white:   '0xD3D7CF'

  # Bright colors
  bright:
    black:   '0x555753'
    red:     '0xEF2929'
    green:   '0x8AE234'
    yellow:  '0xFCE94F'
    blue:    '0x729FCF'
    magenta: '0xAD7FA8'
    cyan:    '0x34E2E2'
    white:   '0xEEEEEC'

# color_end

bell:
  animation: EaseOutExpo
  duration: 0

# Background opacity
background_opacity: 1.0

scrolling:
  # How many lines of scrollback to keep,
  # '0' will disable scrolling.
  history: 50000

  # Number of lines the viewport will move for every line
  # scrolled when scrollback is enabled (history > 0).
  multiplier: 3

# Mouse bindings
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  url:
    launcher: xdg-open
    modifiers: Shift
  hide_when_typing: false


selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

# Live config reload (changes require restart)
live_config_reload: true

# Shell
shell:
  program: /usr/bin/zsh

key_bindings:
  - { key: LBracket, mods: Control, mode: Vi, action: ClearSelection }
  - { key: Q, mode: Vi, action: ScrollToBottom }
  - { key: Q, mode: Vi, action: ToggleViMode }
  # Key: $
  - { key: 05, mods: Shift, mode: Vi, action: Last }
  - { key: 06, mods: Shift, mode: Vi, action: Bracket }
  # Key: 0
  - { key: 07, mods: Shift, mode: Vi, action: FirstOccupied }
