#######################################################################
# Pyenv
#######################################################################

- name: Installing pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: ~/.pyenv

#######################################################################
# Nodeenv
#######################################################################

- name: Installing nodenv
  git:
    repo: https://github.com/nodenv/nodenv.git
    dest: ~/.nodenv

- name: Compiling nodenv source
  command: src/configure && make -C src
  args:
    chdir: ~/.nodenv

- name: Installing node-build
  git:
    repo: https://github.com/nodenv/node-build.git
    dest: ~/.nodenv/plugins/node-build

- name: Installing nodenv-package rehash
  git:
    repo: https://github.com/nodenv/nodenv-package-rehash.git
    dest: ~/.nodenv/plugins/nodenv-package-rehash

#######################################################################
# Java
#######################################################################

- name: Install sdkman
  command: curl -s "https://get.sdkman.io" | bash

#######################################################################
# Goenv
#######################################################################

- name: Install goenv
  git:
    repo: https://github.com/syndbg/goenv.git
    dest: ~/.goenv

#######################################################################
# Rbenv
#######################################################################

- name: Installing rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv

- name: Compiling rbenv source
  command: src/configure && make -C src
  args:
    chdir: ~/.rbenv

- name: Installing ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

#######################################################################
# Tfenv
#######################################################################

- name: Installing tfenv
  git:
    repo: https://github.com/kamatama41/tfenv.git
    dest: ~/.tfenv
