- name: Installing Rust
  command: curl https://sh.rustup.rs -sSf | sh

- name: Installing rust programs
  command: cargo install {{ item }}
  loop: "{{ programs_cargo }}"

- name: Adding rustup components
  command: rustup component add {{ item }}
  loop: "{{ programs_rustup }}"
